version: 3
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "Type: dependencies"
    # Enable version updates for npm
- package-ecosystem: "npm"
  # Look for `package.json` and `lock` files in the `root` directory
  directory: "/components"
  schedule:
    interval: weekly
  labels:
    - "Type: dependencies"
