---
engines:
  duplications:
    exclude_paths:
      - "**/src/test/kotlin/**"
exclude_paths:
  - "README.md"
  - ".github/**"
  - "examples/components/tasklist-angular/**"
  - "examples/components/process-forms/**"
  - "docs/**"
