fixes:
  - "io/holunda/polyflow/polyflow-datapool-api/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-datapool-core/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-datapool-event/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-taskpool-api/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-taskpool-core/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-taskpool-event/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-camunda-bpm-engine-client/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-camunda-bpm-springboot-starter/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-camunda-bpm-taskpool-collector/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-datapool-sender/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-taskpool-sender/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-tasklist-url-resolver/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-variable-serializer/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-view-form-url-resolver/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-view-jpa/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-view-mongo/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-view-simple/::src/main/kotlin/"
  - "io/holunda/polyflow/polyflow-view-view-api/::src/main/kotlin/"
