server:
  port: 8083

spring:
  application:
    name: taskpool-cockpit
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging.level.io.holunda.camunda.taskpool:
  cockpit: INFO



