spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polyflow
    username: polyflow_user
    password: S3Cr3T!
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: "classpath:db/migrations"

polyflow:
  view:
    jpa:
      stored-items: TASK, DATA_ENTRY, PROCESS_DEFINITION
