server:
  port: 8081

spring:
  application:
    name: taskpool
  profiles:
    active: simple # control the view implementation

#axon.serializer:
#  general: jackson
#  events: jackson
#  messages: jackson

polyflow:
  integration:
    form-url-resolver:
      default-task-template:  "tasks/${formKey}/${id}?userId=%userId%"
      default-process-template: "${formKey}?userId=%userId%"
      default-data-entry-template: "${entryType}/${entryId}?userId=%userId%"
      default-application-template: "http://localhost:${server.port}/${applicationName}"
      applications:
        example-process-approval:
          url: "http://localhost:8080/example-process-approval"
          processes:
            process_approve_request: "start?userId=%userId%"
          data-entries:
            io.holunda.camunda.taskpool.example.ApprovalRequest: "approval-request/${entryId}?userId=%userId%"

logging.level:
  io.holunda.polyflow.core:
    taskpool: WARN
    view.simple.service.DataEntryService : DEBUG
    view.simple.service.TaskPoolService : INFO
    example.tasklist: WARN
