server:
  port: 8080
spring:
  application:
    name: example-process-approval
  datasource:
    url: jdbc:postgresql://localhost:5432/process
    username: polyflow_user
    password: S3Cr3T!
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
    database-platform: io.holunda.polyflow.example.infrastructure.NoToastPostgresSQLDialect
    properties:
      hibernate:
        type:
          preferred_instant_jdbc_type: TIMESTAMP
          preferred_uuid_jdbc_type: BINARY
  flyway:
    enabled: true
    locations: "classpath:db/migrations"
  groovy:
    template:
      check-template-location: false

#axon.serializer:
#  general: jackson
#  events: jackson
#  messages: jackson

camunda:
  bpm:
    login:
      enabled: true
      user-id: admin
    admin-user:
      email: admin@local
      id: admin
      first-name: Adminus
      last-name: Administratius
      password: admin
    default-serialization-format: application/json
    eventing:
      task: false
    authorization:
      enabled: false
    history-level: full
    id-generator: strong
    database:
      schema-update: false
      type: postgres
    webapp:
      index-redirect-enabled: false

polyflow:
  integration:
    collector:
      camunda:
        application-name: ${spring.application.name}  # default
        process-instance:
          enabled: true
        process-definition:
          enabled: true
        task:
          enabled: true
          enricher:
            type: processVariables
          importer:
            enabled: true
            task-filter-type: eventstore # FIXME currently this makes no sense here. There is no local event store
    sender:
      enabled: true
      data-entry:
        enabled: true
        type: simple
        application-name: ${spring.application.name}  # default
      process-definition:
        enabled: true
      process-instance:
        enabled: true
      task:
        enabled: true
        type: tx
        send-within-transaction: true # Must be set to true in single node scenario.
    tasklist:
      tasklist-url: http://localhost:8081/polyflow/tasks

logging.level:
  io.holunda.polyflow:
    taskpool:
      gateway: DEBUG
      sender: INFO
      core: WARN
      view.simple: INFO
    datapool:
      sender: INFO
  org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
