server:
  port: 8080

spring:
  profiles:
    active: jpa
  application:
    name: example-process-approval
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: false
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  groovy:
    template:
      check-template-location: false

axon-gateway:
  query:
    type: revision-aware
    revision-aware:
      default-query-timeout: 10
camunda:
  bpm:
    default-serialization-format: application/json
    admin-user:
      id: admin
      first-name: Admin
      last-name: Administrarius
      email: admin@localhost
      password: admin
    filter:
      create: All tasks
    authorization:
      enabled: false
    history-level: full
    id-generator: strong
    database:
      schema-update: true
    webapp:
      index-redirect-enabled: false

polyflow:
  integration:
    client:
      camunda:
        application-name: ${spring.application.name}  # default
    collector:
      camunda:
        application-name: ${spring.application.name}  # default
        process-instance:
          enabled: true
        process-definition:
          enabled: true
        process-variable:
          enabled: true
        task:
          enabled: true
          enricher:
            type: processVariables

    form-url-resolver:
      default-application-template: "http://localhost:${server.port}/${applicationName}"
      default-task-template: "tasks/${formKey}/${id}?userId=%userId%"
      default-process-template: "${formKey}?userId=%userId%"
      applications:
        example-process-approval:
          url: "http://localhost:${server.port}/${spring.application.name}"
          processes:
            process_approve_request: "start?userId=%userId%"
          data-entries:
            io.holunda.camunda.taskpool.example.ApprovalRequest: "approval-request/${entryId}?userId=%userId%"
    sender:
      enabled: true
      data-entry:
        enabled: true
        type: simple
        application-name: ${spring.application.name}  # default
      process-definition:
        enabled: true
      process-instance:
        enabled: true
      process-variable:
        enabled: true
      task:
        enabled: true
        type: tx
        send-within-transaction: true # Must be set to true in single node scenario.
    tasklist:
      tasklist-url: http://localhost:${server.port}/taskpool/tasks
  view:
    jpa:
      payload-attribute-level-limit: 2
      stored-items: task, process-instance, process-definition, data-entry


logging.level:
  io.holunda.camunda:
    taskpool.core: DEBUG
  io.holunda.polyflow:
    taskpool:
      collector:
        process:
          variable: DEBUG
      sender: INFO
      core: WARN
      view.simple: INFO
    datapool:
      sender: INFO
    view.jpa: DEBUG

# To log REST controllers
#  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
# To log web access
# org.springframework.web: DEBUG


