name: CI for branches

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11.0.5']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache .m2
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

      - name: Prepare I-Tests
        run: mkdir -p target/jgiven-reports/json

      - name: Run I-Tests with Maven
        run: ./mvnw integration-test failsafe:verify -Pitest -DskipFrontend -B

      - name: Upload coverage information
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
