name: CI for branches

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: maven

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

        # install is required so the install-browsers step finds all the other modules
      - name: Build with Maven
        run: ./mvnw clean install -U -B -ntp -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

      - name: Prepare I-Tests
        run: mkdir -p target/jgiven-reports/json

      - name: Install Browsers for Playwright
        run: ./mvnw exec:java -B -e -f scenarios/single-node-jpa -Dexec.classpathScope="test" -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run I-Tests with Maven
        run: ./mvnw integration-test failsafe:verify -Pitest -B -ntp

      - name: Upload coverage information
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
