openapi: '3.0.3'
info:
  title: Example Approval Process REST API
  version: 0.0.1
  description: API for the example approval process.

servers:
  - url: http://localhost:8080/example-process-approval/rest
    description: Local example process REST API

tags:
- name: Request
  description: Operations to manipulate requests.
- name: User Task Amend Request
  description: Operations on task amend request.
- name: User Task Approve Request
  description: Operations on task approve request.

paths:
  '/environment':
    get:
      tags:
        - Environment
      summary: Retrieives information about the environment.
      operationId: getEnvironment
      responses:
        200:
          description: Environment can be retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Environment'

  '/request':
    parameters:
      - in: header
        name: X-Current-User-ID
        description: Specifies the id of current user.
        schema:
          type: string
        required: true
      - in: query
        name: revision
        description: Revision of the projection.
        schema:
          type: string
        required: false
    post:
      tags:
        - Request
      summary: Create a new approval request draft and starts approval process.
      operationId: startNewApproval
      requestBody:
        description: Request to be approved.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalRequestDraft'

      responses:
        201:
          description: Sucessful operation.
    get:
      tags:
        - Request
      summary: Retrieves all events known by the projections.
      operationId: getApprovalForUser
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                title: Approval Request List.
                type: array
                items:
                  $ref: '#/components/schemas/ApprovalRequest'

  '/request/{id}':
    parameters:
      - in: header
        name: X-Current-User-ID
        description: Specifies the id of current user.
        schema:
          type: string
        required: true
      - in: path
        name: id
        schema:
          type: string
        description: Request id.
        required: true
    get:
      tags:
        - Request
      summary: Loads request for specified id.
      operationId: getApprovalRequest
      responses:
        200:
          description: Sucessful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalRequest'

  '/approve-request/id/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Task id.
        required: true
      - in: header
        name: X-Current-User-ID
        description: Specifies the id of current user.
        schema:
          type: string
        required: true
    get:
      tags:
        - User Task Approve Request
      summary: Retrieves information about the task approve request with specified id.
      operationId: loadTaskApproveRequestFormData
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskApproveRequestFormData'
    post:
      tags:
        - User Task Approve Request
      summary: Receives form data for the completion of the task approve request with specified id.
      requestBody:
        description: Payload to be added to the process instance on task completion.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskApproveRequestSubmitData'
      operationId: submitTaskApproveRequestSubmitData
      responses:
        201:
          description: Successful operation.

  '/amend-request/id/{id}':
    parameters:
      - in: path
        name: id
        schema:
          type: string
        description: Task id.
        required: true
      - in: header
        name: X-Current-User-ID
        description: Specifies the id of current user.
        schema:
          type: string
        required: true
    get:
      tags:
        - User Task Amend Request
      summary: Retrieves information about the task amend request with specified id.
      operationId: loadTaskAmendRequestFormData
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskAmendRequestFormData'
    post:
      tags:
        - User Task Amend Request
      summary: Receives form data for the completion of the task amend request with specified id.
      requestBody:
        description: Payload to be added to the process instance on task completion.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskAmendRequestSubmitData'
      operationId: submitTaskAmendRequestSubmitData
      responses:
        201:
          description: Successful operation.

components:
  schemas:

    Task:
      type: object
      properties:
        id:
          type: string
          description: Id of the user task.
        name:
          type: string
          description: Action to execute.
        description:
          type: string
          description: Description of the user task.
        formKey:
          type: string
          description: Form key of the task (as defined in the process model).
        assignee:
          type: string
          description: User name of assigned user.
        createTime:
          type: string
          description: Creation date and time of the task.
          format: date-time
        dueDate:
          type: string
          description: Due date and time of the task.
          format: date-time
        followUpDate:
          type: string
          description: Follow-up date and time of the task.
          format: date-time
        priority:
          type: integer
          description: Priority of the task.
      required:
      - id
      - name
      - description
      - createTime
      - dueDate
      - businessKey

    ApprovalRequestDraft:
      type: object
      properties:
        amount:
          type: number
          format: float
        currency:
          type: string
        subject:
          type: string
        applicant:
          type: string
      required:
        - applicant
        - subject
        - amount
        - currency

    ApprovalRequest:
      type: object
      properties:
        id:
          type: string
        subject:
          type: string
        applicant:
          type: string
        amount:
          type: number
          format: float
        currency:
          type: string
      required:
        - id
        - applicant
        - subject
        - amount
        - currency

    TaskApproveRequestFormData:
      type: object
      properties:
        task:
          $ref: '#/components/schemas/Task'
        approvalRequest:
          $ref: '#/components/schemas/ApprovalRequest'
      required:
        - task
        - approvalRequest

    TaskAmendRequestFormData:
      type: object
      properties:
        task:
          $ref: '#/components/schemas/Task'
        approvalRequest:
          $ref: '#/components/schemas/ApprovalRequest'
        comment:
          type: string
          description: Comment of the approver.
      required:
        - task
        - approvalRequest

    TaskApproveRequestSubmitData:
      type: object
      properties:
        decision:
          type: string
          description: One of 'APPROVE', 'REJECT' or 'RETURN' denoting the decition of the approver.
        comment:
          type: string
          description: Optional comment.
      required:
        - decision

    TaskAmendRequestSubmitData:
      type: object
      properties:
        action:
          type: string
          description: One of 'CANCEL' or 'RESUBMIT' actions reflecting the decision of the originator, how to proceed with the request.
        approvalRequest:
          $ref: '#/components/schemas/ApprovalRequest'
        comment:
          type: string
          description: Optional comment.
      required:
        - action

    Environment:
      type: object
      properties:
        applicationName:
          type: string
          description: Name of this process application.
        tasklistUrl:
          type: string
          description: URL of the tasklist.
